baseURL = 'https://up.ac.cn/'
languageCode = 'zh-CN'
title = '@Plato 海伟 | 烧钱美学家'
copyright = "Copyright © 2022, Plato."
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"
[params]
  description = "Home 页面的TDK描述内容"
  favicon = "images/favicon.png"
  title = "2022年跨境出海数字营销如何有效烧钱"
  dateFormat = "2006-01-02"
  gid = "G-96Z4V0B7J7"
[author]
  name = 'Plato 海伟'